#!/bin/sh

PROJECT_ROOT=".."
RESOURCES_DIR="${PROJECT_ROOT}/resources"
DEFAULT_PAGES_DIR="${RESOURCES_DIR}/defaults"
BUILD_DIR="${PROJECT_ROOT}/build"

SERVICE_SCRIPT_NAME="WebServerd.service"
WS_CONFIG_DIR="/etc/WebServerd"
CONFIG_FILE_NAME="WebServerd.conf"
RESOURCES_CONFIG_FILE_NAME="resources.conf"
RSA_CERT_FILE_NAME="rsa.crt"
RSA_PRIV_KEY_FILE_NAME="rsa.key"
ECDSA_CERT_FILE_NAME="ecdsa.crt"
ECDSA_PRIV_KEY_FILE_NAME="ecdsa.key"

CONFIG_FILE="${RESOURCES_DIR}/${CONFIG_FILE_NAME}"
CONFIG_FILE_PATH="${WS_CONFIG_DIR}/${CONFIG_FILE_NAME}"
RESOURCES_CONFIG_FILE="${RESOURCES_DIR}/${RESOURCES_CONFIG_FILE_NAME}"
RESOURCES_CONFIG_FILE_PATH="${WS_CONFIG_DIR}/${RESOURCES_CONFIG_FILE_NAME}"

RSA_CERT="${RESOURCES_DIR}/${RSA_CERT_FILE_NAME}"
RSA_PRIV_KEY="${RESOURCES_DIR}/${RSA_PRIV_KEY_FILE_NAME}"
ECDSA_CERT="${RESOURCES_DIR}/${ECDSA_CERT_FILE_NAME}"
ECDSA_PRIV_KEY="${RESOURCES_DIR}/${ECDSA_PRIV_KEY_FILE_NAME}"


SERVICE_SCRIPT="${RESOURCES_DIR}/${SERVICE_SCRIPT_NAME}"
SERVICE_SCRIPT_DIR="/lib/systemd/system"
WS_RESOURCES_DIR="/var/WebServerd"
WS_DEFAULT_PAGES_DIR="${WS_RESOURCES_DIR}/defaults"
WS_TEMPORARY_FILES_DIR="${WS_RESOURCES_DIR}/.tmpfiles"
USER_NAME="wsd"
GROUP_NAME="wsd"
WS_DAEMON_NAME="WebServerd"
WS_DAEMON_PATH="${BUILD_DIR}/${WS_DAEMON_NAME}"
WS_DAEMON_BIN_PATH="/sbin"

